import { useEffect, useRef, useState } from "react";
import {
  Box,
  Heading,
  SimpleGrid,
  Card,
  CardBody,
  Spinner,
  Text,
  Flex,
  Spacer,
  Tooltip,
  Icon,
  Button,
  Menu,
  MenuButton,
  MenuList,
  MenuItem,
  HStack,
} from "@chakra-ui/react";

import { DownloadIcon } from "@chakra-ui/icons";
import { FiDownload, FiFileText, FiFile } from "react-icons/fi";

import useAuth from "../hooks/useAuth";
import expenseService from "../services/expenseService";
import profileService from "../services/profileService";
import { toast } from "../utils/toast";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";

import { Pie, Bar } from "react-chartjs-2";

import {
  Chart as ChartJS,
  ArcElement,
  Tooltip as ChartTooltip,
  Legend,
  CategoryScale,
  LinearScale,
  BarElement,
  PointElement,
  LineElement,
} from "chart.js";

ChartJS.register(
  ArcElement,
  ChartTooltip,
  Legend,
  CategoryScale,
  LinearScale,
  BarElement,
  PointElement,
  LineElement
);

export default function Dashboard() {
  const { user } = useAuth();
  const effectRan = useRef(false);
  const [monthlyData, setMonthlyData] = useState([]);
  const [categoryData, setCategoryData] = useState([]);
  const [summary, setSummary] = useState({
    totalSpent: 0,
    highestCategory: null,
    avgMonthly: 0,
  });
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!effectRan.current) {
      loadDashboardData();
      loadCountries();
      effectRan.current = true;
    }
  }, []);

  const loadCountries = async () => {
    try {
      const res = await profileService.countries();
      localStorage.setItem("countries", JSON.stringify(res.data));
    } catch (error) {
      console.error("Error loading countries:", error);
    }
  };

  const loadDashboardData = async () => {
    try {
      const [monthly, categories, summaryData] = await Promise.all([
        expenseService.getMonthlyExpenses(user.id),
        expenseService.getCategoryExpenses(user.id),
        expenseService.getSummary(user.id),
      ]);

      setMonthlyData(monthly);
      setCategoryData(categories);
      setSummary(summaryData);
    } finally {
      setLoading(false);
    }
  };

  const downloadData = async (type) => {
    const response = await expenseService.exportData();
    const data = response.exportDetails;
    if (data.length === 0) {
      toast.error("No data found");
      return;
    }

    switch (type) {
      case "excel":
        exportExcel(data, response.name);
        break;

      case "pdf":
        exportPDF(data, response.name);
        break;

      default:
        console.error("Unknown type:", type);
    }

  };

  const exportExcel = (data, userName) => {
    const formattedData = data.map(row => {
      const formatted = {};
      Object.keys(row).forEach(key => {
        formatted[key.toUpperCase()] = formatINR(row[key]);
      });
      return formatted;
    });

    const worksheet = XLSX.utils.json_to_sheet(formattedData);
    const workbook = XLSX.utils.book_new();

    XLSX.utils.book_append_sheet(workbook, worksheet, `${userName} Report`);

    XLSX.writeFile(workbook, `Expenses_${userName.replace(/\s/g, "_")}.xlsx`);
  };

  const exportPDF = (data, userName) => {
    const doc = new jsPDF();

    doc.setFontSize(16);
    doc.text(`Expense Report`, 14, 10);

    doc.setFontSize(12);
    doc.text(`Generated By: ${userName}`, 14, 20);

    const headers = [Object.keys(data[0]).map(h => h.toUpperCase())];
    const rows = data.map(item =>
      Object.keys(item).map(key => formatINR(item[key]))
    );

    autoTable(doc, {
      startY: 30,
      head: headers,
      body: rows,
    });

    doc.save(`Expenses_${userName.replace(/\s/g, "_")}.pdf`);
  };

  const formatINR = (value) => {
    if (typeof value === "number") {
      return new Intl.NumberFormat("en-IN", {
        style: "currency",
        currency: "INR",
        minimumFractionDigits: 2,
      }).format(value);
    }
    return value;
  };

  const CATEGORY_COLORS = [
    "#4C6FFF",
    "#FF6B6B",
    "#FFD93D",
    "#6BCB77",
    "#A66BFF",
    "#FF922B",
    "#20C997",
    "#E8308C",
    "#17A2B8",
    "#FF8C00",
    "#8A2BE2",
    "#00BFA5",
    "#FF1744",
    "#D500F9",
    "#C0CA33"
  ];

  const formatCurrency = (amount) => {
    return new Intl.NumberFormat("en-IN", {
      style: "currency",
      currency: "INR",
      minimumFractionDigits: 2,
    }).format(amount);
  };

  if (loading) {
    return (
      <Flex justify="center" align="center" minH="60vh">
        <Spinner size="xl" />
      </Flex>
    );
  }

  return (
    <Box maxW="7xl" mx="auto" p={6}>
      {/* HEADER */}
      <Flex align="center" mb={8}>
        <Heading size="lg">
          Welcome, {user?.name || user?.email} 👋
        </Heading>

        <Spacer />

        {/* DOWNLOAD BUTTON WITH DROPDOWN */}
        <Menu>
          <MenuButton
            as={Button}
            colorScheme="blue"
            rightIcon={<FiDownload />}
            size="md"
            borderRadius="md"
            shadow="sm"
          >
            Export To
          </MenuButton>

          <MenuList
            minW="fit-content"
            px={2}
            py={1}
            borderRadius="md"
            shadow="lg"
          >
            <MenuItem
              icon={<FiFileText />}
              onClick={() => downloadData("excel")}
              fontSize="sm"
              _hover={{ bg: "green.50", color: "green.600" }}
              px={3}
            >
              Excel (.xlsx)
            </MenuItem>

            <MenuItem
              icon={<FiFile />}
              onClick={() => downloadData("pdf")}
              fontSize="sm"
              _hover={{ bg: "red.50", color: "red.600" }}
              px={3}
            >
              PDF (.pdf)
            </MenuItem>
          </MenuList>
        </Menu>

      </Flex>

      {/* SUMMARY CARDS */}
      <SimpleGrid columns={{ base: 1, md: 3 }} spacing={6} mb={8}>
        <Card shadow="sm">
          <CardBody textAlign="center">
            <Heading size="md">₹{summary.totalSpent ? formatCurrency(summary.totalSpent) : 0}/-</Heading>
            <Text>Total Spent</Text>
          </CardBody>
        </Card>

        <Card shadow="sm">
          <CardBody textAlign="center">
            <Heading size="md">{summary.highestCategory?.category ?? "—"}</Heading>
            <Text>Top Category</Text>
          </CardBody>
        </Card>

        <Card shadow="sm">
          <CardBody textAlign="center">
            <Heading size="md">₹{summary.avgMonthly ? formatCurrency(summary.avgMonthly) : 0}/-</Heading>
            <Text>Avg Monthly Spend</Text>
          </CardBody>
        </Card>
      </SimpleGrid>

      {/* CHARTS */}
      <SimpleGrid columns={{ base: 1, md: 2 }} spacing={8}>
        {/* Pie Chart */}
        <Card shadow="sm" borderRadius="lg" height="300px">
          <CardBody>
            <Heading size="md" mb={4} textAlign="center">
              Monthly Expense Overview
            </Heading>

            <Box height="200px">
              {monthlyData.length === 0 ? (
                <Text textAlign="center" color="gray.500">No Data Available</Text>
              ) : (
                <Pie
                  data={{
                    labels: monthlyData.map((m) => m.month),
                    datasets: [
                      {
                        data: monthlyData.map((m) => m.total),
                        backgroundColor: [
                          "#4C6FFF",
                          "#FF6B6B",
                          "#FFD93D",
                          "#6BCB77",
                          "#A66BFF",
                          "#FF922B",
                        ],
                      },
                    ],
                  }}
                  options={{
                    maintainAspectRatio: false,
                    plugins: { legend: { position: "bottom" } },
                  }}
                />
              )}
            </Box>
          </CardBody>
        </Card>

        {/* Bar Chart */}
        <Card shadow="sm" borderRadius="lg" height="300px">
          <CardBody>
            <Heading size="md" mb={4} textAlign="center">
              Expense Trend by Category
            </Heading>

            <Box height="200px">
              {categoryData.length === 0 ? (
                <Text textAlign="center" color="gray.500">No Data Available</Text>
              ) : (
                <Bar
                  data={{
                    labels: categoryData.map((c) => c.category),
                    datasets: [
                      {
                        label: "Amount Spent",
                        data: categoryData.map((c) => c.amount),
                        backgroundColor: categoryData.map((_, index) =>
                          CATEGORY_COLORS[index % CATEGORY_COLORS.length]
                        ),
                      },
                    ],
                  }}
                  options={{
                    responsive: true,
                    maintainAspectRatio: false,
                    plugins: { legend: { display: false } },
                    scales: {
                      x: { type: "category" },
                      y: { beginAtZero: true },
                    },
                  }}
                />
              )}
            </Box>
          </CardBody>
        </Card>
      </SimpleGrid>
    </Box>
  );
}
